AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Nested stacks - Root template 
Resources:
  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/sg.yaml
      TimeoutInMinutes: 20
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/ec2.yaml
      TimeoutInMinutes: 20
      Parameters:
        SecurityGroupIds: !GetAtt SGStack.Outputs.SGID
Outputs:
  WebsiteURL:
    Value: !GetAtt EC2Stack.Outputs.InstanceIP
