AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Nested stacks - Root template 
Parameters:
  S3BucketName:
    Description: S3 bucket name for the Nested Stacks. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: String
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: Bucket name can include numbers, lowercase letters, uppercase letters, periods (.), and hyphens (-). It cannot start or end with a hyphen (-).
  EC2NameTag:
    Description: Name Tag of EC2
    Type: String
Resources:
  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/sg.yaml
      TimeoutInMinutes: 20
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/ec2.yaml
      TimeoutInMinutes: 20
      Parameters:
        SecurityGroupIds: !GetAtt SGStack.Outputs.SGID
        Tags: 
          Ref: EC2NameTag
Outputs:
  WebsiteURL:
    Value: !GetAtt EC2Stack.Outputs.InstanceIP
