AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Security group with 22 port open
Resources:
  ec2sg:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SG to allow SSH to EC2
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
Outputs:
  SGID:
    Value:
      Fn::GetAtt:
      - ec2sg
      - GroupId
    Description: SG Id